// Generated by gencpp from file navigation/PlannerRequest.msg
// DO NOT EDIT!


#ifndef NAVIGATION_MESSAGE_PLANNERREQUEST_H
#define NAVIGATION_MESSAGE_PLANNERREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <navigation/Point_xy.h>
#include <navigation/Point_xy.h>
#include <navigation/PolyArray.h>

namespace navigation
{
template <class ContainerAllocator>
struct PlannerRequest_
{
  typedef PlannerRequest_<ContainerAllocator> Type;

  PlannerRequest_()
    : start()
    , goal()
    , obstacle_list()  {
    }
  PlannerRequest_(const ContainerAllocator& _alloc)
    : start(_alloc)
    , goal(_alloc)
    , obstacle_list(_alloc)  {
  (void)_alloc;
    }



   typedef  ::navigation::Point_xy_<ContainerAllocator>  _start_type;
  _start_type start;

   typedef  ::navigation::Point_xy_<ContainerAllocator>  _goal_type;
  _goal_type goal;

   typedef  ::navigation::PolyArray_<ContainerAllocator>  _obstacle_list_type;
  _obstacle_list_type obstacle_list;





  typedef boost::shared_ptr< ::navigation::PlannerRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::navigation::PlannerRequest_<ContainerAllocator> const> ConstPtr;

}; // struct PlannerRequest_

typedef ::navigation::PlannerRequest_<std::allocator<void> > PlannerRequest;

typedef boost::shared_ptr< ::navigation::PlannerRequest > PlannerRequestPtr;
typedef boost::shared_ptr< ::navigation::PlannerRequest const> PlannerRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::navigation::PlannerRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::navigation::PlannerRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace navigation

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'navigation': ['/home/tyjo/catkin_ws_o/test_codes/Trotbot/trotbot_ws/src/navigation/msg', '/home/tyjo/catkin_ws_o/test_codes/Trotbot/trotbot_ws/src/navigation/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::navigation::PlannerRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::navigation::PlannerRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::navigation::PlannerRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::navigation::PlannerRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::navigation::PlannerRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::navigation::PlannerRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::navigation::PlannerRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "312cafca219eff06ca8155401fd152ea";
  }

  static const char* value(const ::navigation::PlannerRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x312cafca219eff06ULL;
  static const uint64_t static_value2 = 0xca8155401fd152eaULL;
};

template<class ContainerAllocator>
struct DataType< ::navigation::PlannerRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "navigation/PlannerRequest";
  }

  static const char* value(const ::navigation::PlannerRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::navigation::PlannerRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "navigation/Point_xy start\n\
navigation/Point_xy goal\n\
navigation/PolyArray obstacle_list\n\
\n\
================================================================================\n\
MSG: navigation/Point_xy\n\
float32[] point\n\
================================================================================\n\
MSG: navigation/PolyArray\n\
navigation/PointArray[] polygons\n\
\n\
================================================================================\n\
MSG: navigation/PointArray\n\
navigation/Point_xy[] points\n\
  \n\
";
  }

  static const char* value(const ::navigation::PlannerRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::navigation::PlannerRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.start);
      stream.next(m.goal);
      stream.next(m.obstacle_list);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PlannerRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::navigation::PlannerRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::navigation::PlannerRequest_<ContainerAllocator>& v)
  {
    s << indent << "start: ";
    s << std::endl;
    Printer< ::navigation::Point_xy_<ContainerAllocator> >::stream(s, indent + "  ", v.start);
    s << indent << "goal: ";
    s << std::endl;
    Printer< ::navigation::Point_xy_<ContainerAllocator> >::stream(s, indent + "  ", v.goal);
    s << indent << "obstacle_list: ";
    s << std::endl;
    Printer< ::navigation::PolyArray_<ContainerAllocator> >::stream(s, indent + "  ", v.obstacle_list);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NAVIGATION_MESSAGE_PLANNERREQUEST_H
