// Generated by gencpp from file navigation/PlannerResponse.msg
// DO NOT EDIT!


#ifndef NAVIGATION_MESSAGE_PLANNERRESPONSE_H
#define NAVIGATION_MESSAGE_PLANNERRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <navigation/PointArray.h>

namespace navigation
{
template <class ContainerAllocator>
struct PlannerResponse_
{
  typedef PlannerResponse_<ContainerAllocator> Type;

  PlannerResponse_()
    : path()
    , ack(false)  {
    }
  PlannerResponse_(const ContainerAllocator& _alloc)
    : path(_alloc)
    , ack(false)  {
  (void)_alloc;
    }



   typedef  ::navigation::PointArray_<ContainerAllocator>  _path_type;
  _path_type path;

   typedef uint8_t _ack_type;
  _ack_type ack;





  typedef boost::shared_ptr< ::navigation::PlannerResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::navigation::PlannerResponse_<ContainerAllocator> const> ConstPtr;

}; // struct PlannerResponse_

typedef ::navigation::PlannerResponse_<std::allocator<void> > PlannerResponse;

typedef boost::shared_ptr< ::navigation::PlannerResponse > PlannerResponsePtr;
typedef boost::shared_ptr< ::navigation::PlannerResponse const> PlannerResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::navigation::PlannerResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::navigation::PlannerResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace navigation

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'navigation': ['/home/tyjo/catkin_ws_o/test_codes/Trotbot/trotbot_ws/src/navigation/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::navigation::PlannerResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::navigation::PlannerResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::navigation::PlannerResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::navigation::PlannerResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::navigation::PlannerResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::navigation::PlannerResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::navigation::PlannerResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7dbb4339dd73402726335b4f58e3f859";
  }

  static const char* value(const ::navigation::PlannerResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7dbb4339dd734027ULL;
  static const uint64_t static_value2 = 0x26335b4f58e3f859ULL;
};

template<class ContainerAllocator>
struct DataType< ::navigation::PlannerResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "navigation/PlannerResponse";
  }

  static const char* value(const ::navigation::PlannerResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::navigation::PlannerResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "navigation/PointArray path\n\
bool ack\n\
\n\
================================================================================\n\
MSG: navigation/PointArray\n\
std_msgs/Header header\n\
geometry_msgs/Point[] points\n\
  \n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::navigation::PlannerResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::navigation::PlannerResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.path);
      stream.next(m.ack);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PlannerResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::navigation::PlannerResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::navigation::PlannerResponse_<ContainerAllocator>& v)
  {
    s << indent << "path: ";
    s << std::endl;
    Printer< ::navigation::PointArray_<ContainerAllocator> >::stream(s, indent + "  ", v.path);
    s << indent << "ack: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.ack);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NAVIGATION_MESSAGE_PLANNERRESPONSE_H
