// Generated by gencpp from file navigation/PolyArray.msg
// DO NOT EDIT!


#ifndef NAVIGATION_MESSAGE_POLYARRAY_H
#define NAVIGATION_MESSAGE_POLYARRAY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <navigation/PointArray.h>

namespace navigation
{
template <class ContainerAllocator>
struct PolyArray_
{
  typedef PolyArray_<ContainerAllocator> Type;

  PolyArray_()
    : polygons()  {
    }
  PolyArray_(const ContainerAllocator& _alloc)
    : polygons(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::navigation::PointArray_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::navigation::PointArray_<ContainerAllocator> >::other >  _polygons_type;
  _polygons_type polygons;





  typedef boost::shared_ptr< ::navigation::PolyArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::navigation::PolyArray_<ContainerAllocator> const> ConstPtr;

}; // struct PolyArray_

typedef ::navigation::PolyArray_<std::allocator<void> > PolyArray;

typedef boost::shared_ptr< ::navigation::PolyArray > PolyArrayPtr;
typedef boost::shared_ptr< ::navigation::PolyArray const> PolyArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::navigation::PolyArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::navigation::PolyArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace navigation

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'navigation': ['/home/tyjo/catkin_ws_o/test_codes/Trotbot/trotbot_ws/src/navigation/msg', '/home/tyjo/catkin_ws_o/test_codes/Trotbot/trotbot_ws/src/navigation/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::navigation::PolyArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::navigation::PolyArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::navigation::PolyArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::navigation::PolyArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::navigation::PolyArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::navigation::PolyArray_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::navigation::PolyArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "49d5f4357e9c5ac38b54c91ae2b7c9f3";
  }

  static const char* value(const ::navigation::PolyArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x49d5f4357e9c5ac3ULL;
  static const uint64_t static_value2 = 0x8b54c91ae2b7c9f3ULL;
};

template<class ContainerAllocator>
struct DataType< ::navigation::PolyArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "navigation/PolyArray";
  }

  static const char* value(const ::navigation::PolyArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::navigation::PolyArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "navigation/PointArray[] polygons\n\
\n\
================================================================================\n\
MSG: navigation/PointArray\n\
navigation/Point_xy[] points\n\
  \n\
================================================================================\n\
MSG: navigation/Point_xy\n\
float32[] point\n\
";
  }

  static const char* value(const ::navigation::PolyArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::navigation::PolyArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.polygons);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PolyArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::navigation::PolyArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::navigation::PolyArray_<ContainerAllocator>& v)
  {
    s << indent << "polygons[]" << std::endl;
    for (size_t i = 0; i < v.polygons.size(); ++i)
    {
      s << indent << "  polygons[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::navigation::PointArray_<ContainerAllocator> >::stream(s, indent + "    ", v.polygons[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // NAVIGATION_MESSAGE_POLYARRAY_H
